DEMO_NODES = [
    # AI & Machine Learning
    {"title": "Large Language Models", "content": "Large language models (LLMs) are neural networks trained on massive text corpora. They demonstrate emergent capabilities like reasoning, code generation, and complex instruction following. GPT-4, Claude, and Gemini represent the frontier of this technology.", "category": "AI", "tags": ["nlp", "deep-learning", "transformers"]},
    {"title": "Transformer Architecture", "content": "The transformer architecture revolutionized NLP with self-attention mechanisms. It enables parallel processing of sequences and captures long-range dependencies, forming the backbone of modern AI systems.", "category": "AI", "tags": ["architecture", "attention", "neural-networks"]},
    {"title": "Reinforcement Learning from Human Feedback", "content": "RLHF aligns language models with human preferences by training reward models on human comparisons and using reinforcement learning to optimize model outputs toward those preferences.", "category": "AI", "tags": ["alignment", "rlhf", "training"]},
    {"title": "Vector Databases", "content": "Vector databases store high-dimensional embeddings and enable semantic similarity search at scale. They power recommendation systems, semantic search, and retrieval-augmented generation.", "category": "AI", "tags": ["database", "embeddings", "search"]},
    {"title": "Multimodal AI", "content": "Multimodal AI systems process and generate multiple data types including text, images, audio, and video. They enable richer interactions and can understand context across modalities.", "category": "AI", "tags": ["vision", "audio", "generative"]},
    {"title": "AI Agents", "content": "AI agents are autonomous systems that perceive their environment, plan actions, and execute tasks to achieve goals. They combine language models with tool use and memory for complex workflows.", "category": "AI", "tags": ["agents", "autonomy", "planning"]},
    {"title": "Retrieval Augmented Generation", "content": "RAG combines vector search with language model generation, grounding AI responses in retrieved documents. It reduces hallucination and enables knowledge-intensive tasks without full fine-tuning.", "category": "AI", "tags": ["rag", "retrieval", "generation"]},

    # Fintech
    {"title": "Decentralized Finance", "content": "DeFi recreates traditional financial systems using blockchain and smart contracts. It enables permissionless lending, borrowing, trading, and yield generation without intermediaries.", "category": "Fintech", "tags": ["blockchain", "defi", "web3"]},
    {"title": "Embedded Finance", "content": "Embedded finance integrates financial services directly into non-financial apps. E-commerce platforms offering instant credit, ride-sharing apps with instant driver payouts, and SaaS tools with built-in payment rails.", "category": "Fintech", "tags": ["payments", "banking", "api"]},
    {"title": "Real-Time Payments", "content": "Real-time payment rails like FedNow and RTP enable instant fund transfers 24/7. They're transforming B2B payments, payroll, and gig economy compensation models.", "category": "Fintech", "tags": ["payments", "banking", "infrastructure"]},
    {"title": "AI Fraud Detection", "content": "Machine learning models analyze transaction patterns in milliseconds to detect fraudulent activity. Graph neural networks identify suspicious networks while anomaly detection flags unusual behavior.", "category": "Fintech", "tags": ["fraud", "ml", "security"]},
    {"title": "Open Banking", "content": "Open banking APIs let third parties access bank account data with customer consent. They enable personal finance management, automated savings, and seamless account verification.", "category": "Fintech", "tags": ["api", "banking", "data"]},

    # Climate Tech
    {"title": "Carbon Capture Technology", "content": "Direct air capture machines chemically bind atmospheric CO2 for storage or utilization. Combined with renewable energy, they could become a significant tool for removing legacy carbon emissions.", "category": "Climate", "tags": ["carbon", "capture", "climate"]},
    {"title": "Green Hydrogen", "content": "Green hydrogen produced via electrolysis powered by renewables offers a clean fuel for hard-to-decarbonize sectors like steel, shipping, and aviation. Falling electrolyzer costs are accelerating adoption.", "category": "Climate", "tags": ["hydrogen", "energy", "decarbonization"]},
    {"title": "Vertical Farming", "content": "Vertical farms grow crops in stacked indoor layers with controlled environments. They use 95% less water than conventional farming, eliminate pesticides, and enable local food production year-round.", "category": "Agriculture", "tags": ["farming", "food", "sustainability"]},
    {"title": "Precision Agriculture", "content": "IoT sensors, drones, and AI analyze crop health, soil conditions, and weather to optimize inputs. Precision agriculture reduces waste, increases yields, and minimizes environmental impact.", "category": "Agriculture", "tags": ["iot", "drones", "farming"]},
    {"title": "Ocean Energy Harvesting", "content": "Wave, tidal, and thermal ocean energy converters tap the ocean's vast renewable energy potential. Advanced materials and mooring systems are making offshore deployments increasingly viable.", "category": "Climate", "tags": ["energy", "ocean", "renewables"]},
    {"title": "Solid State Batteries", "content": "Solid-state batteries replace liquid electrolytes with solid materials, offering higher energy density, faster charging, and improved safety. They could transform EVs and grid-scale energy storage.", "category": "Climate", "tags": ["batteries", "energy", "ev"]},

    # Robotics & Hardware
    {"title": "Humanoid Robots", "content": "Next-generation humanoid robots combine advanced locomotion, dexterous manipulation, and AI reasoning. They're being deployed in warehouses, healthcare, and manufacturing environments.", "category": "Robotics", "tags": ["humanoid", "automation", "hardware"]},
    {"title": "Swarm Robotics", "content": "Swarm robotics coordinates hundreds of simple robots to accomplish complex tasks collectively. Inspired by ant colonies and bee swarms, they enable resilient distributed systems.", "category": "Robotics", "tags": ["swarm", "distributed", "automation"]},
    {"title": "Neuromorphic Computing", "content": "Neuromorphic chips mimic the brain's neural structure for ultra-efficient AI inference. They process sparse, event-driven data with minimal power, enabling edge AI at scale.", "category": "Computing", "tags": ["chips", "brain", "edge-ai"]},
    {"title": "Quantum Computing", "content": "Quantum computers harness superposition and entanglement to solve certain problems exponentially faster. Near-term applications include optimization, drug discovery, and cryptographic analysis.", "category": "Computing", "tags": ["quantum", "computing", "physics"]},

    # Health Tech
    {"title": "AI Drug Discovery", "content": "Machine learning accelerates drug discovery by predicting protein structures, molecular interactions, and clinical trial outcomes. AlphaFold's protein structure predictions have transformed structural biology.", "category": "HealthTech", "tags": ["drug-discovery", "proteins", "ml"]},
    {"title": "Digital Therapeutics", "content": "Software-based interventions deliver evidence-based therapeutic interventions to patients. FDA-cleared digital therapeutics treat conditions from diabetes to ADHD using behavioral science and AI.", "category": "HealthTech", "tags": ["therapeutics", "digital-health", "fda"]},
    {"title": "Brain-Computer Interfaces", "content": "BCIs create direct communication channels between brains and computers. They enable paralyzed patients to control devices with thought, and may eventually augment healthy human cognition.", "category": "HealthTech", "tags": ["bci", "neuroscience", "hardware"]},
    {"title": "Synthetic Biology", "content": "Synthetic biology engineers biological systems for applications from biofuels to living medicines. CRISPR enables precise genetic editing while cell-free systems enable rapid prototyping.", "category": "HealthTech", "tags": ["biology", "crispr", "engineering"]},

    # Space & Deep Tech
    {"title": "Satellite Internet Constellations", "content": "Low-earth orbit satellite constellations provide global broadband coverage. Starlink, OneWeb, and Amazon Kuiper are connecting remote regions and enabling new maritime and aviation applications.", "category": "SpaceTech", "tags": ["satellites", "internet", "leo"]},
    {"title": "Space Manufacturing", "content": "Microgravity enables manufacturing of materials impossible on Earth including ultra-pure fiber optics, novel alloys, and pharmaceutical compounds. Returning to Earth creates high-value exports.", "category": "SpaceTech", "tags": ["manufacturing", "space", "materials"]},
    {"title": "Autonomous Vehicles", "content": "Self-driving vehicles combine computer vision, LiDAR, radar, and AI to navigate environments safely. They promise to transform logistics, reduce accidents, and enable mobility for underserved populations.", "category": "Robotics", "tags": ["av", "autonomy", "transportation"]},
]
